services:
  kickassmtgbot:
    container_name: kickassmtgbot_di
    build: 
        context: .
        dockerfile: Dockerfile
    image: kickassmtgdiscordbot
    restart: always
    volumes:
      - /home/discordbotdata/kickassmtg/Data:/app/Data
    networks:
      - ravendb-compose_ravendb_net
    env_file:
      - access-keys.env
volumes:
  kickassmtgbot:
networks: 
  ravendb-compose_ravendb_net:
    external: true