services:
  kickassmtgbot:
    container_name: kickassmtgbot_di
    build: 
        context: .
        dockerfile: docker/kickassmtg/Dockerfile
    image: kickassmtgdiscordbot
    restart: always
    volumes:
      - /home/discordbotdata/kickassmtg/Data:/app/Data
    networks:
      - ravendb-compose_ravendb_net
volumes:
  kickassmtgbot:
networks: 
  ravendb-compose_ravendb_net:
    external: true
  